### ISSUE TITLE
AttributeError: 'DataFrame' object has no attribute 'sort'

### ISSUE THREAD

**Issue by alexandruioanvoda** [slowkow/snpsea#5]
Hi! Package looks great, can't wait to use it!

Unfortunately, running the tutorial I got this error:

```
$ snpsea-barplot out
/home/avoda/bin/snpsea-barplot:67: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  pvalues = pd.read_table(f_pvalues, index_col=0)
/home/avoda/bin/snpsea-barplot:74: FutureWarning: read_table is deprecated, use read_csv instead, passing sep='\t'.
  index_col=0).drop('Description', axis=1)
Traceback (most recent call last):
  File "/home/avoda/bin/snpsea-barplot", line 250, in <module>
    main()
  File "/home/avoda/bin/snpsea-barplot", line 61, in main
    top=int(args['--top']))
  File "/home/avoda/bin/snpsea-barplot", line 84, in barplot
    pvalues = pvalues.sort('pvalue')[:top]
  File "/gfs/devel/avoda/miniconda3/lib/python2.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'sort'
```

Seems like the Python calls a deprecated `sort` function? https://stackoverflow.com/a/44123892/11265666

Any help would be appreciated.

**Comment by slowkow** [comment]
Thanks for opening this issue! It looks like the pandas package has changed a lot since 2014, when I wrote the Python script for making a figure.

After you successfully run SNPSEA, you should have a file like this:

```
column -t pvalues.txt
name                       pvalue      nulls_observed  nulls_tested
Colorectal_Adenocarcinoma  0.598007    179             300
Whole_Blood                0.179743    125             700
BM-CD33+Myeloid            0.0230122   144             6300
PB-CD14+Monocytes          0.256776    179             700
PB-BDCA4+Dentritic_cells   0.174037    121             700
PB-CD56+NK_cells           0.00356157  181             51100
PB-CD4+T_cells             8.4844e-05  138             1638300
```

The columns are as follows:

- name: The name of the column in your gene expression matrix.
- pvalue: The SNPSEA p-value after testing random sets of SNPs.
- nulls_observed: The number of random SNP sets with a statistic more extreme than your given SNP set.
- nulls_tested: The total number of random SNP sets tested for this cell type.

For example, `(138 + 1) / (1638300 + 1) = 0.00008484399`

Since the `snpsea-barplot` script is not working, I would suggest that you try plotting the values with your preferred tools.
